/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DimensionScores = IDL.Record({
  'em' : IDL.Float64,
  'pm' : IDL.Float64,
  'edi' : IDL.Float64,
  'iai' : IDL.Float64,
  'rrm' : IDL.Float64,
  'sis' : IDL.Float64,
});
export const Time = IDL.Int;
export const AssessmentResult = IDL.Record({
  'id' : IDL.Text,
  'dimensionScores' : DimensionScores,
  'responses' : IDL.Vec(IDL.Int),
  'archetype' : IDL.Text,
  'timestamp' : Time,
  'decisionForceLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAssessmentResult' : IDL.Func([IDL.Text], [AssessmentResult], ['query']),
  'getRecentResults' : IDL.Func([], [IDL.Vec(AssessmentResult)], ['query']),
  'submitAssessment' : IDL.Func(
      [IDL.Vec(IDL.Int), DimensionScores, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DimensionScores = IDL.Record({
    'em' : IDL.Float64,
    'pm' : IDL.Float64,
    'edi' : IDL.Float64,
    'iai' : IDL.Float64,
    'rrm' : IDL.Float64,
    'sis' : IDL.Float64,
  });
  const Time = IDL.Int;
  const AssessmentResult = IDL.Record({
    'id' : IDL.Text,
    'dimensionScores' : DimensionScores,
    'responses' : IDL.Vec(IDL.Int),
    'archetype' : IDL.Text,
    'timestamp' : Time,
    'decisionForceLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'getAssessmentResult' : IDL.Func([IDL.Text], [AssessmentResult], ['query']),
    'getRecentResults' : IDL.Func([], [IDL.Vec(AssessmentResult)], ['query']),
    'submitAssessment' : IDL.Func(
        [IDL.Vec(IDL.Int), DimensionScores, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };